export default function AudioAgent() {
  return (
    <div className="flex flex-col gap-12 max-w-6xl">
      {/* HEADER */}
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">
          Audio Agent
        </h1>
        <p className="opacity-70 mt-2 leading-relaxed max-w-2xl">
          The audio intelligence agent responsible for generating music prompts,
          ambient layers, emotional scoring logic, cultural sound palettes, and
          world‑aware audio reasoning. The Audio Agent uses the Agent Kernel for
          context, reasoning, and routing.
        </p>
      </div>
      {/* AUDIO MODES */}
      <section>
        <h2 className="text-xl font-medium mb-4">Audio Modes</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Music Mode",
            "Ambient Mode",
            "Emotion Mode",
            "Culture Sound Mode",
            "Scene Score Mode",
            "Voice Tone Mode",
          ].map((mode) => (
            <div
              key={mode}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{mode}</h3>
              <p className="opacity-70 text-sm mt-1">Switch mode</p>
            </div>
          ))}
        </div>
      </section>
      {/* CONTEXT LOADERS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Context Loaders</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Load Character Context",
            "Load Culture Context",
            "Load Universe Context",
            "Load Realm Context",
            "Load Timeline Context",
            "Load Scene Context",
          ].map((ctx) => (
            <div
              key={ctx}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{ctx}</h3>
              <p className="opacity-70 text-sm mt-1">Attach context</p>
            </div>
          ))}
        </div>
      </section>
      {/* WORKSPACE */}
      <section>
        <h2 className="text-xl font-medium mb-4">Audio Workspace</h2>
        <div className="grid grid-cols-[2fr,1fr] gap-6">
          {/* LEFT: GENERATION PANEL */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4 min-h-[360px]">
            <div className="opacity-70 text-sm">
              Audio preview area (connect to backend). Displays music prompts,
              ambient layers, emotional scoring logic, and cultural sound
              expansions generated by the Audio Agent.
            </div>
            <textarea
              className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-sm outline-none resize-none h-40"
              placeholder="Describe the music, ambient layer, emotional tone, or cultural sound you want the Audio Agent to generate..."
            />
            <div className="flex gap-3 mt-3">
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Generate
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Refine
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Route to Pipeline
              </button>
            </div>
            <p className="opacity-50 text-[11px] mt-2">
              The Audio Agent uses the Agent Kernel for context, reasoning, and
              routing to other engines.
            </p>
          </div>
          {/* RIGHT: CONTEXT + ROUTING */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4">
            <h3 className="font-medium text-sm">Active Context</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Character: Aruwa — Dawn Incarnate</li>
              <li>• Culture: Diaspora Culture Grid</li>
              <li>• Universe: Diaspora Storyworld v3</li>
              <li>• Realm: Diaspora Realm</li>
              <li>• Timeline: Diaspora Timeline</li>
              <li>• Scene: Dawn Arrival Sequence</li>
            </ul>
            <h3 className="font-medium text-sm mt-4">Routing Targets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Music Engine Pro</li>
              <li>• Voice Engine Pro</li>
              <li>• Motion Engine Pro</li>
              <li>• Script Engine Pro</li>
              <li>• Story Agent</li>
              <li>• Asset Pipeline Engine</li>
            </ul>
            <h3 className="font-medium text-sm mt-4">Presets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• High‑mythic sound</li>
              <li>• Culture‑driven palette</li>
              <li>• Emotion‑centric scoring</li>
              <li>• Ambient world‑soul textures</li>
            </ul>
          </div>
        </div>
      </section>
      {/* SYSTEMS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Audio Agent Systems</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Audio Engine",
            "Palette Engine",
            "Emotion Engine",
            "Audio Archive",
            "Audio Analytics",
            "Agent Settings",
          ].map((sys) => (
            <div
              key={sys}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{sys}</h3>
              <p className="opacity-70 text-sm mt-1">Open system</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
