export default function StoryAgent() {
  return (
    <div className="flex flex-col gap-12 max-w-6xl">

      {/* HEADER */}
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">
          Story Agent
        </h1>
        <p className="opacity-70 mt-2 leading-relaxed max-w-2xl">
          The narrative intelligence agent responsible for generating scenes,
          episodes, arcs, beats, lore, and mythic‑cultural storytelling. The
          Story Agent uses the Agent Kernel for context, reasoning, and routing.
        </p>
      </div>

      {/* STORY MODES */}
      <section>
        <h2 className="text-xl font-medium mb-4">Story Modes</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Scene Mode",
            "Episode Mode",
            "Arc Mode",
            "Beat Mode",
            "Lore Mode",
            "Mythic Mode",
          ].map((mode) => (
            <div
              key={mode}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{mode}</h3>
              <p className="opacity-70 text-sm mt-1">Switch mode</p>
            </div>
          ))}
        </div>
      </section>

      {/* CONTEXT LOADERS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Context Loaders</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Load Universe Context",
            "Load Realm Context",
            "Load Character Context",
            "Load Culture Context",
            "Load Timeline Context",
            "Load Arc Context",
          ].map((ctx) => (
            <div
              key={ctx}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{ctx}</h3>
              <p className="opacity-70 text-sm mt-1">Attach context</p>
            </div>
          ))}
        </div>
      </section>

      {/* WORKSPACE */}
      <section>
        <h2 className="text-xl font-medium mb-4">Story Workspace</h2>
        <div className="grid grid-cols-[2fr,1fr] gap-6">

          {/* LEFT: GENERATION PANEL */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4 min-h-[360px]">
            <div className="opacity-70 text-sm">
              Story preview area (connect to narrative backend). Displays scenes,
              arcs, beats, and lore generated by the Story Agent.
            </div>

            <textarea
              className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-sm outline-none resize-none h-40"
              placeholder="Describe the scene, episode, arc, or lore you want the Story Agent to generate..."
            />

            <div className="flex gap-3 mt-3">
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Generate
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Refine
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Route to Pipeline
              </button>
            </div>

            <p className="opacity-50 text-[11px] mt-2">
              The Story Agent uses the Agent Kernel for context, reasoning, and
              routing to other engines.
            </p>
          </div>

          {/* RIGHT: CONTEXT + ROUTING */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4">

            <h3 className="font-medium text-sm">Active Context</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Universe: Diaspora Storyworld v3</li>
              <li>• Realm: Diaspora Realm</li>
              <li>• Character: Aruwa — Dawn Incarnate</li>
              <li>• Culture: Diaspora Culture Grid</li>
              <li>• Timeline: Diaspora Timeline</li>
              <li>• Arc: Diaspora Hero Arc</li>
            </ul>

            <h3 className="font-medium text-sm mt-4">Routing Targets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Script Engine Pro</li>
              <li>• Image Engine Pro</li>
              <li>• Motion Engine Pro</li>
              <li>• Voice Engine Pro</li>
              <li>• Music Engine Pro</li>
              <li>• Asset Pipeline Engine</li>
            </ul>

            <h3 className="font-medium text-sm mt-4">Presets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• High‑mythic storytelling</li>
              <li>• Culture‑driven narrative</li>
              <li>• Character‑centric scenes</li>
              <li>• System‑design exposition</li>
            </ul>

          </div>
        </div>
      </section>

      {/* SYSTEMS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Story Agent Systems</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Narrative Engine",
            "Context Engine",
            "Reasoning Engine",
            "Story Archive",
            "Story Analytics",
            "Agent Settings",
          ].map((sys) => (
            <div
              key={sys}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{sys}</h3>
              <p className="opacity-70 text-sm mt-1">Open system</p>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
}
