export default function CharacterAgent() {
  return (
    <div className="flex flex-col gap-12 max-w-6xl">

      {/* HEADER */}
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">
          Character Agent
        </h1>
        <p className="opacity-70 mt-2 leading-relaxed max-w-2xl">
          The character intelligence agent responsible for generating character
          sheets, emotional arcs, personality vectors, dialogue, voice DNA, and
          relational dynamics. The Character Agent uses the Agent Kernel for
          context, reasoning, and routing.
        </p>
      </div>

      {/* CHARACTER MODES */}
      <section>
        <h2 className="text-xl font-medium mb-4">Character Modes</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Character Sheet Mode",
            "Backstory Mode",
            "Dialogue Mode",
            "Emotion Mode",
            "Relationship Mode",
            "Voice DNA Mode",
          ].map((mode) => (
            <div
              key={mode}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{mode}</h3>
              <p className="opacity-70 text-sm mt-1">Switch mode</p>
            </div>
          ))}
        </div>
      </section>

      {/* CONTEXT LOADERS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Context Loaders</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Load Character Context",
            "Load Culture Context",
            "Load Universe Context",
            "Load Realm Context",
            "Load Timeline Context",
            "Load Arc Context",
          ].map((ctx) => (
            <div
              key={ctx}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{ctx}</h3>
              <p className="opacity-70 text-sm mt-1">Attach context</p>
            </div>
          ))}
        </div>
      </section>

      {/* WORKSPACE */}
      <section>
        <h2 className="text-xl font-medium mb-4">Character Workspace</h2>
        <div className="grid grid-cols-[2fr,1fr] gap-6">

          {/* LEFT: GENERATION PANEL */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4 min-h-[360px]">
            <div className="opacity-70 text-sm">
              Character preview area (connect to backend). Displays character
              sheets, emotional variants, dialogue, and relational dynamics
              generated by the Character Agent.
            </div>

            <textarea
              className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-sm outline-none resize-none h-40"
              placeholder="Describe the character, dialogue, emotion, or relationship you want the Character Agent to generate..."
            />

            <div className="flex gap-3 mt-3">
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Generate
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Refine
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Route to Pipeline
              </button>
            </div>

            <p className="opacity-50 text-[11px] mt-2">
              The Character Agent uses the Agent Kernel for context, reasoning,
              and routing to other engines.
            </p>
          </div>

          {/* RIGHT: CONTEXT + ROUTING */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4">

            <h3 className="font-medium text-sm">Active Context</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Character: Aruwa — Dawn Incarnate</li>
              <li>• Culture: Diaspora Culture Grid</li>
              <li>• Universe: Diaspora Storyworld v3</li>
              <li>• Realm: Diaspora Realm</li>
              <li>• Timeline: Diaspora Timeline</li>
              <li>• Arc: Diaspora Hero Arc</li>
            </ul>

            <h3 className="font-medium text-sm mt-4">Routing Targets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Script Engine Pro</li>
              <li>• Voice Engine Pro</li>
              <li>• Image Engine Pro</li>
              <li>• Story Agent</li>
              <li>• Asset Pipeline Engine</li>
              <li>• Character Genome Engine</li>
            </ul>

            <h3 className="font-medium text-sm mt-4">Presets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• High‑mythic character design</li>
              <li>• Culture‑driven personality</li>
              <li>• Emotion‑centric storytelling</li>
              <li>• Relationship‑driven dynamics</li>
            </ul>

          </div>
        </div>
      </section>

      {/* SYSTEMS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Character Agent Systems</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Character Engine",
            "Context Engine",
            "Reasoning Engine",
            "Character Archive",
            "Character Analytics",
            "Agent Settings",
          ].map((sys) => (
            <div
              key={sys}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{sys}</h3>
              <p className="opacity-70 text-sm mt-1">Open system</p>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
}
