export default function PipelineAgent() {
  return (
    <div className="flex flex-col gap-12 max-w-6xl">
      {/* HEADER */}
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">
          Pipeline Agent
        </h1>
        <p className="opacity-70 mt-2 leading-relaxed max-w-2xl">
          The operational intelligence agent responsible for auto‑tagging,
          auto‑routing, auto‑archiving, metadata syncing, and asset validation.
          The Pipeline Agent ensures all creative outputs flow smoothly across
          Hegay OS. It uses the Agent Kernel for context, reasoning, and routing.
        </p>
      </div>
      {/* PIPELINE MODES */}
      <section>
        <h2 className="text-xl font-medium mb-4">Pipeline Modes</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Tagging Mode",
            "Routing Mode",
            "Archive Mode",
            "Metadata Mode",
            "Validation Mode",
            "Sync Mode",
          ].map((mode) => (
            <div
              key={mode}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{mode}</h3>
              <p className="opacity-70 text-sm mt-1">Switch mode</p>
            </div>
          ))}
        </div>
      </section>
      {/* CONTEXT LOADERS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Context Loaders</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Load Asset Context",
            "Load Metadata Context",
            "Load Universe Context",
            "Load Realm Context",
            "Load Character Context",
            "Load Culture Context",
          ].map((ctx) => (
            <div
              key={ctx}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{ctx}</h3>
              <p className="opacity-70 text-sm mt-1">Attach context</p>
            </div>
          ))}
        </div>
      </section>
      {/* WORKSPACE */}
      <section>
        <h2 className="text-xl font-medium mb-4">Pipeline Workspace</h2>
        <div className="grid grid-cols-[2fr,1fr] gap-6">
          {/* LEFT: OPERATION PANEL */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4 min-h-[360px]">
            <div className="opacity-70 text-sm">
              Pipeline preview area (connect to backend). Displays asset metadata,
              routing decisions, tagging suggestions, and archive operations
              generated by the Pipeline Agent.
            </div>
            <textarea
              className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-sm outline-none resize-none h-40"
              placeholder="Describe the asset or pipeline operation you want the Pipeline Agent to perform..."
            />
            <div className="flex gap-3 mt-3">
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Process
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Validate
              </button>
              <button className="px-4 py-2 rounded-md bg-white/10 border border-white/20 text-sm hover:bg-white/20 transition">
                Route
              </button>
            </div>
            <p className="opacity-50 text-[11px] mt-2">
              The Pipeline Agent uses the Agent Kernel for context, reasoning,
              and routing across all Pro Engines.
            </p>
          </div>
          {/* RIGHT: CONTEXT + ROUTING */}
          <div className="p-6 rounded-xl bg-white/5 border border-white/10 flex flex-col gap-4">
            <h3 className="font-medium text-sm">Active Context</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Asset Type: Script / Image / Motion / Voice / Music</li>
              <li>• Universe: Diaspora Storyworld v3</li>
              <li>• Realm: Diaspora Realm</li>
              <li>• Character: Aruwa — Dawn Incarnate</li>
              <li>• Culture: Diaspora Culture Grid</li>
              <li>• Metadata: Synced</li>
            </ul>
            <h3 className="font-medium text-sm mt-4">Routing Targets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Script Engine Pro</li>
              <li>• Image Engine Pro</li>
              <li>• Motion Engine Pro</li>
              <li>• Music Engine Pro</li>
              <li>• Voice Engine Pro</li>
              <li>• Story Agent</li>
              <li>• World Agent</li>
              <li>• Character Agent</li>
              <li>• Visual Agent</li>
              <li>• Audio Agent</li>
              <li>• Asset Pipeline Engine</li>
            </ul>
            <h3 className="font-medium text-sm mt-4">Presets</h3>
            <ul className="text-sm opacity-80 space-y-1">
              <li>• Auto‑tag assets</li>
              <li>• Auto‑route assets</li>
              <li>• Auto‑archive assets</li>
              <li>• Auto‑sync metadata</li>
            </ul>
          </div>
        </div>
      </section>
      {/* SYSTEMS */}
      <section>
        <h2 className="text-xl font-medium mb-4">Pipeline Agent Systems</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            "Tagging Engine",
            "Routing Engine",
            "Archive Engine",
            "Metadata Engine",
            "Pipeline Analytics",
            "Agent Settings",
          ].map((sys) => (
            <div
              key={sys}
              className="p-5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition cursor-pointer"
            >
              <h3 className="font-medium">{sys}</h3>
              <p className="opacity-70 text-sm mt-1">Open system</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
